force-app/main/default/objects/Contact/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <formula>TEXT(Height_Feet__c) &amp; &apos;Feet&apos; &amp;  TEXT(Height_Inches__c) &amp; &apos;Inches&apos;</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Height</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Center</fullName>
            </value>
            <value>
                <fullName>Forward</fullName>
            </value>
            <value>
                <fullName>Forward-Center</fullName>
            </value>
            <value>
                <fullName>Guard</fullName>
            </value>
            <value>
                <fullName>Guard-Forward</fullName>
            </value>
            <value>
                <fullName>Unknown</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/ServerId__c.field-meta.xml
<CustomField>
    <fullName>ServerId__c</fullName>
    <label>ServerId</label>
    <precision>15</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Team__c.field-meta.xml
<CustomField>
    <fullName>Team__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Team</label>
    <referenceTo>Team__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/FantasyTeam__c/FantasyTeam__c.object-meta.xml
<CustomObject>
    <label>FantasyTeam</label>
    <nameField>
        <displayFormat>FT-{0000000000}</displayFormat>
        <label>FantasyTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FantasyTeams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FanTeamPlayer__c/FanTeamPlayer__c.object-meta.xml
<CustomObject>
    <label>FanTeamPlayer</label>
    <nameField>
        <displayFormat>FTP-{000000000}</displayFormat>
        <label>FanTeamPlayer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FanTeamPlayers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/FanTeamPlayer__c/fields/FantasyTeam__c.field-meta.xml
<CustomField>
    <fullName>FantasyTeam__c</fullName>
    <label>FantasyTeam</label>
    <referenceTo>FantasyTeam__c</referenceTo>
    <relationshipLabel>FanTeamPlayers</relationshipLabel>
    <relationshipName>FanTeamPlayers</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/FanTeamPlayer__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FanTeamPlayers</relationshipLabel>
    <relationshipName>FanTeamPlayers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Team__c/Team__c.object-meta.xml
<CustomObject>
    <label>Team</label>
    <nameField>
        <label>Team Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Teams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Team__c/fields/ServerId__c.field-meta.xml
<CustomField>
    <fullName>ServerId__c</fullName>
    <label>ServerId</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/SearchPlayersController.cls
public without sharing class SearchPlayersController {
    
    @AuraEnabled
    public static List<Team__c> getNBATeams(){
        try {
            List<Team__c> NBATeams = [SELECT id, Name FROM Team__c]; 
        	return NBATeams;  
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage() );
        }       
    }
    
    @AuraEnabled
    public static List<Contact> getNBATeamPlayers(String NBATeamId) {
        
        try {
            List<Contact> teamPlayers = new List<Contact>();
            Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NBA Player').getRecordTypeId();
            
            if (String.isEmpty(NBATeamId) || NBATeamId == null || NBATeamId == ' '){
                teamPlayers = [SELECT Name, Position__c, Height__c, Weight__c FROM Contact 
                           WHERE 	RecordTypeId 	= :recordTypeId ]; 
            } else {
                teamPlayers = [SELECT Name, Position__c, Height__c, Weight__c FROM Contact 
                           WHERE 	Team__c 		= :NBATeamId AND
                                	RecordTypeId 	= :recordTypeId ]; 
            }
                       
            return teamPlayers;    
            
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage() ); 
        }
        
    }
    
    @AuraEnabled
    public static void addPlayerToTeam(Id fanteam , Contact player){
        try {
             FanTeamPlayer__c ftp = new FanTeamPlayer__c (Player__c = player.Id , FantasyTeam__C = fanteam);
        
       		 insert ftp;
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage() ); 
        }
 
        
    }
    
    @AuraEnabled
    public static List<Contact> searchPlayerByName(String name){
        
        try {
            Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('NBA Player').getRecordTypeId();
            return [SELECT FirstName, LastName, Name,  Position__c, Team__r.Name, ServerId__c FROM Contact 
                    WHERE RecordTypeId 	= :recordTypeId AND
                   		 (FirstName LIKE :name+'%' OR LastName LIKE :name+'%' OR Name LIKE :name+'%')] ; 
            
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage()); 
        }
        
        
    }
    
    @AuraEnabled 
    public static List<DataSet> getLastSeasonStats(String ServerId) {
        
        List<DataSet> dataSet = new List<DataSet>();     
        Map<String,Decimal> stats = PlayerStats.getAverStats('2018', ServerId); 
        
        Set<String> keys = stats.keySet();        
        for(String k : keys) {
            Decimal total = stats.get(k); 
            dataSet.add(new DataSet(k ,total));
        }
        
        return dataSet;
        
    }
    
    
    public class DataSet{
        public DataSet(String label ,Decimal count){
            this.label  = label ; 
            this.count = count ;
        }
        @AuraEnabled
        public String label {get;set;}
        @AuraEnabled
        public Decimal  count {get;set;}
        
        
    }

}