force-app/main/default/objects/Contact/recordTypes/FantasyPlayer.recordType-meta.xml
<RecordType>
    <fullName>FantasyPlayer</fullName>
    <active>true</active>
    <label>FantasyPlayer</label>
</RecordType>

force-app/main/default/objects/FantasyTeam__c/FantasyTeam__c.object-meta.xml
<CustomObject>
    <label>FantasyTeam</label>
    <nameField>
        <displayFormat>FT-{0000000000}</displayFormat>
        <label>FantasyTeam Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>FantasyTeams</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/FantasyTeam__c/fields/FantasyPlayer__c.field-meta.xml
<CustomField>
    <fullName>FantasyPlayer__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>FantasyPlayer</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>FantasyTeams</relationshipLabel>
    <relationshipName>FantasyTeams</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/FantasyTeams.cls
public class FantasyTeams {

    
    @AuraEnabled
    public static void createTeam(FantasyTeam__c fanTeam){
        try {
            Id userId = System.UserInfo.getUserId(); 
            User us = [SELECT contactId  FROM user WHERE id=:userId];
            
            Id recordTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('FantasyPlayer').getRecordTypeId();
            
            Contact con = [Select Id, Name FROM Contact WHERE id =:us.ContactId and RecordTypeId = :recordTypeId ]; 
            
            fanTeam.FantasyPlayer__c = con.Id; 
            
            insert fanTeam;    
            
        } catch (Exception e) {
            throw new AuraHandledException('Server-side Error: ' + e.getMessage()); 
        }     
        
    }
    
    
}